spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.33/sell?characterEncoding=utf-8&useSSL=false

spring:
  dubbo:
    application:
      name: login_user
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.dhxl33.login_user.service